server:
  port: 8082
spring:
  application:
    name: security-spring-client
  datasource:
    url: jdbc:mysql://localhost:3306/db-security
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/spring-secu
          jwk-set-uri: http://localhost:8080/realms/spring-secu/protocol/openid-connect/certs
